// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://htjtumxyjjtqnsakimrl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh0anR1bXh5amp0cW5zYWtpbXJsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4MzIyNTEsImV4cCI6MjA2NjQwODI1MX0.3Wg-5VN_yAqB_2e46U8fE8yV_Rc4B9MzMeBRCiZTuQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);